a=int(input("enter a value:"))
b=int(input("enter b value:"))
print("addition :",a+b)
print("subtraction :",a-b)
print("multiplication :",a*b)
print("division :",a/b)
print("floor division :",a//b)
print("expontential :",a**b)
print("modulus :",a%b)
